baseURL = "https://parkerqueen.github.io"
languageCode = "en-us"
title = "Parker Queen"
theme="archie"

copyright = "Â© parkerqueen"

# Code highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Articles per page
paginate=3

[params]
	mode="dark"
	useCDN=false
	subtitle = "Software Engineer | Computer Scientist"

# Social tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/parkerqueen"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:sobanr4@gmail.com"

